CREATE DATABASE IF NOT EXISTS d3stats_staging;

USE d3stats_staging;

CREATE TABLE IF NOT EXISTS usr (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL UNIQUE,
	pass VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS difficulty (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS run (
	id INT(11) NOT NULL AUTO_INCREMENT,
	start_time DATETIME,
	end_time DATETIME,
	total_time DATETIME NOT NULL,
	map_id INT(11) NOT NULL,
	xp_gain INT(20),
	legend_drops INT(11),
	goblin_count INT(11),
	gold_gain INT(20),
	y_mobs INT(11),
	b_mobs INT(11),
	p_mobs INT(11),
	difficulty INT(11),
	notes VARCHAR(5000),
	usr_id INT(11),
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS map (
	id INT(11) NOT NULL AUTO_INCREMENT,
	act INT(11) NOT NULL,
	name VARCHAR(1000),
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bounty (
	id INT(11) NOT NULL AUTO_INCREMENT,
	map_id INT(11) NOT NULL,
	name VARCHAR(1000),
	PRIMARY KEY (id)
);


